server: 
  port: 9002
spring: 
  application:  
    name: tensquare-recruit #指定服务名
  datasource:
    url: jdbc:mysql://192.168.56.30:3306/tensquare_recruit?characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa: 
    database: MySQL
    show-sql: true
